# Generated by Django 4.1.5 on 2023-02-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='UpdateAt',
            new_name='updateAt',
        ),
    ]
