# Generated by Django 4.1.5 on 2023-02-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_updateat_message_updateat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='users',
        ),
    ]
